### PR TITLE
Fix issues with `uname`

### LINKED ISSUE #48: Windows 10 compatibility
Hello 👋, is the plugin supposed to work under windows? [This line](
https://github.com/Automattic/measure-builds-gradle-plugin/blob/2d91340817cd6f9d1dd4084ab1cb15142b12ccb3/measure-builds/src/main/java/com/automattic/android/measure/providers/BuildDataProvider.kt#L39) seems to break the gradle build as `uname` is not a Windows command.

my project `build.gradle.kts`
```
plugins {
    id("com.automattic.android.measure-builds") version "3.0.0"
}

measureBuilds {
    enable = true
}
```

The error I got
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'XXXXX'.
> A problem occurred starting process 'command 'uname''
```

Thanks for the response

### PR DESCRIPTION
**Pull request by jkmassel**
In JDK21 on Macs, CLI invocations using `exec` from Gradle plugins fail for security reasons (see https://github.com/Automattic/wordpress-rs/pull/898 for more context).

This PR adjusts how we get the current architecture to avoid this issue (and _possibly_ addresses #48)

---

Closes: #48

### CODE REVIEW

**Comment by wzieba** [comment]
@jkmassel 👋 thanks for the report and fix! To follow up on our discussion on DM, I've decided to propose us using `os.arch` system property, as using the `ProcessBuilder` introduced some issues with configuration cache. 

Getting properties from `System.properties` should work flawlessly, as it does with `operatingSystem()` method.

The values between `uname` and `os.arch` can be different, but it's not a big deal.

Please, tell me @jkmassel if this looks good to you. If so, I'll merge and release the fix!

File: measure-builds/src/test/java/com/automattic/android/measure/MachineDataProviderTest.kt [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+
+class MachineDataProviderTest {
+
+    @Test
+    fun testArchitectureLookup() {
+        val actual = MachineDataProvider().architecture()
+        val expected = System.getProperty("os.arch")
+        println("Architecture: $actual (expected: $expected)")
+        assertEquals(expected, actual)
+    }
```
Comment (wzieba) [inline measure-builds/src/test/java/com/automattic/android/measure/MachineDataProviderTest.kt:28]: Now when I think of it, maybe a test in this form is not really helpful, I guess I should revert to specific values

**Comment by wzieba** [comment]
I'll go ahead and merge this, I'm pretty confident it's a safe solution that fixes the problem!
